version: "3"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: wurstmeister/kafka
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
  
  # dashboard:
  #   image: metabase/metabase
  #   container_name: dashboard
  #   ports:
  #     - "3000:3000"
  #   # networks:
  #   #   - stack
  
  # mongo:
  #   container_name: mongodb
  #   image: mongo:latest
  #   hostname: mongo
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: delanole
  #     MONGO_INITDB_ROOT_PASSWORD: Spdax123
  #   ports:
  #     - 27017:27017
#     networks:
#       - stack
#     depends_on:
#       - mongo
    
# networks:
#   stack:
#     driver: bridge
